library(glmnet)
library(doMC)
library(survival)
library(data.table)
library(mltools)
library(CoxBoost)
library(randomForestSRC)
library(CoxHD)
source('run_prognosis.R')

df_final <- read.table("df_prognosis_features_ready.tsv",sep = '\t' , header = T)
x <- data.matrix(df_final[,1:84])
y <- data.matrix(df_final[,c("os","os_status")])
predictors <- c(predictorGLM)
#predictors <- c(rep(list(predictorGLM),10),rep(list(predictorRF),10),predictorBoost,predictorRFX)
str_predictors <-c(rep("CoxMod",10),rep("RFS",10),"CoxBoost","RFX")
l_alpha <-seq(0.1,1,0.1)
l_ntree <- seq(100,1000,100)
write.table(launch_prognosis(x,y,predictors,str_predictors,l_alpha,l_ntree),"tests.tsv",quote=F,sep='\t')